### PR TITLE
Generic types

### PR DESCRIPTION
**Pull request by davegurnell**
This PR adds generic Decl/Ref support. Caveats:

- it's only currently supported in the DSL (no shapeless derivation);
- no Elm support (because I don't know the syntax).

### CODE REVIEW

**Comment by pvillega** [comment]
LGTM 👍 Good solution to that issue, I was stuck on shapeless and couldn't find my way out of that 'point of view' :) 👏 

I will add Elm later on, when merged. Or you rather I do it in this PR?

**Comment by davegurnell** [comment]
Ok great -- I'm happy to merge if you're happy to fix it in post. I'm using
the feature in a project so It'll be useful for me to publish a
non-snapshot build now :)

On 4 April 2019 at 10:47:06, Pere Villega (notifications@github.com) wrote:

LGTM 👍 Good solution to that issue, I was stuck on shapeless and couldn't
find my way out of that 'point of view' :) 👏

I will add Elm later on, when merged. Or you rather I do it in this PR?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/davegurnell/bridges/pull/21#issuecomment-479829069>,
or mute
the thread

**Comment by pvillega** [comment]
Yes merge ahead!

**Comment by pvillega** [comment]
I added the encoder/decoder for Elm as we discussed. I think we can merge and publish :)

**Comment by davegurnell** [comment]
This is looking great -- thanks very much!

**Pull request merged**
